{% set version = "1.14.3" %}

package:
  name: pysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PySAL/PySAL-{{ version }}.tar.gz
  sha256: e2145c5c5bdfa7c1989154037dba8385ede5aa21354e2d5278705ac902d06a31

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - scipy
  run:
    - python
    - scipy

test:
  imports:
    - pysal

about:
  home: http://pysal.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Library of spatial analysis functions.'

extra:
  recipe-maintainers:
    - sjsrey
    - ocefpaf
