{% set version = "1.14.4.post1" %}

package:
  name: pysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PySAL/PySAL-{{ version }}.tar.gz
  sha256: 396ea62dcb228f80587aabb867315214ad9e891436fb6416a9ae46eb01258315

build:
  number: 1
  script:
    - dos2unix pysal/spreg/utils.py   # [win]
    - dos2unix pysal/spreg/probit.py  # [win]
    - dos2unix pysal/spreg/twosls.py  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
#    - m2-base
#    - m2-filesystem
    - m2-dos2unix
  host:
    - python
    - setuptools
  run:
    - python
    - scipy >=0.11
    - numpy

test:
  imports:
    - pysal

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Library of spatial analysis functions'
  description: |
    PySAL(Python Spatial Analysis Library) is written in Python intended to support the
    development of high level applications.
  doc_url: http://pysal.readthedocs.io/en/latest/index.html
  doc_source_url: https://github.com/pysal/pysal/blob/master/doc/source/index.rst
  dev_url: https://github.com/pysal

extra:
  recipe-maintainers:
    - sjsrey
    - ocefpaf
