{% set version = "1.14.4" %}

package:
  name: pysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PySAL/PySAL-{{ version }}.tar.gz
  sha256: a6f7cff5e26075b070155734079f65dc566e095162263c068646211f1ea9067b

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - scipy >=0.11
    - numpy >=1.3

test:
  imports:
    - pysal

about:
  home: http://pysal.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Library of spatial analysis functions.'

extra:
  recipe-maintainers:
    - sjsrey
    - ocefpaf
