{% set name = "pysal" %}
{% set version = "25.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca1452a1d57811cbc4708002a38ece6fe58b8597f966b310731e2e4014ddf21b

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
  run:
    - beautifulsoup4 >=4.10
    - geopandas >=0.10.0
    - numpy >=1.22
    - packaging >=22
    - pandas >=1.4
    - platformdirs >=2.0.2
    - requests >=2.27
    - scipy >=1.8
    - shapely >=2.0.1
    - scikit-learn >=1.1
    - libpysal >=4.13.0
    - access >=1.1.9
    - esda >=2.7.1
    - giddy >=2.3.6
    - inequality >=1.1.2
    - pointpats >=2.5.1
    - segregation >=2.5.2
    - spaghetti >=1.7.6
    - mgwr >=2.2.1
    - momepy >=0.10.0
    - spglm >=1.1.0
    - spint >=1.0.7
    - spreg >=1.8.3
    - tobler >=0.12.1
    - mapclassify >=2.10.0
    - splot >=1.1.7
    - spopt >=0.7.0
  run_constrained:
    - joblib >=1.2
    - networkx >=2.7
    - numba >=0.55
    - pyarrow >=7.0
    - sqlalchemy >=2.0
    - xarray >=2022.3

test:
  source_files:
    - pysal/tests
  requires:
    - python
    - pip
    - pytest
  imports:
    - pysal
    - pysal.viz
    - pysal.explore
    - pysal.model
    - pysal.lib
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv pysal/tests

about:
  home: https://github.com/pysal/pysal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library of spatial analysis functions
  description: |
    PySAL(Python Spatial Analysis Library) for spatial data science and the development of high level applications.
  doc_url: https://pysal.org/docs
  dev_url: https://github.com/pysal/pysal

extra:
  recipe-maintainers:
    - sjsrey
    - ocefpaf
    - mariusvniekerk
    - marcelotrevisani
