travis:
  secure:
    BINSTAR_TOKEN: XRyjOF8o11ezTOTaiUk+HeNZjoFuJtfn2l2IxnqsRebRNOP+Kl47KYAJwVOqqSWzVIwfIzAq4VIyy6fwowgFW7KT1auDTWhotGAZHvuAu0unDakbAlfHxrotbp+BkzJHhOkr9RSZtab6533fOk5cnxmXX/NUK2izau7tVIcHO9HqREBXqffCqecnnblqpq25QgfurlE72/+Y1G/9dWEQzSXbowrQYpu8YrCJJYDsG9zFzcTAxLpb/Bo4PuNyPzins9lw0uz+dNG2n9PQY8K0PU64ZeF5ZJsabkA2sba3tXIPlgGrTCw7uAJIbizHwa6J+k/wpoBOI+8abxMBB4poqWE6F+m6jWgLab9Un/uSpJCq4Fz0zwe8ctFlsTue6TXgV8WAgsCGQae4BnaQ2EUG/c/6wOqGGweUpi9BvScy3Ck7wYFKvzHxumOJrrjbEWsSWEkXLpHMuolhK7yOeeVE4C1lZNd2F2AUJno6oHzP1aLNGaok+fgAlaHmT6huMNjnavayiChIgB1aQTzesmueIfy10d2DqGqsnkN2b4dNW41HhoNyQ4solrfTpZaqxI7tXRhDUOeRqUygRxvPgdehaQGwn9ujaJPQRwpMzQy8kddegMr3hLjrm0UkPWikA6F6ij9VnwyGEe186PPjer0AkE1sx2YtAYZ5+0qryldnKJw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
